# Generated by Django 2.1.5 on 2019-02-13 20:24

from django.db import migrations, DatabaseError


def resave_all_runeinstance(apps, schema_editor):
    RuneInstance = apps.get_model('herders', 'RuneInstance')

    for rune in RuneInstance.objects.filter(substats__len=0, substat_1__isnull=False):
        try:
            rune.save(update_fields=[
                'substats',
                'substat_values',
                'substat_crafts',
                'substat_craft_values',
            ])
        except DatabaseError:
            # An error can occur if saving with update_fields specified does not actually update anything
            # This can safely be ignored.
            pass


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0002_auto_20190212_1322'),
    ]

    operations = [
        migrations.RunPython(resave_all_runeinstance, noop)
    ]
